#ifndef  _MENU_ID_
#define  _MENU_ID_
/*If a id's fourth number is 1 , imply that it's father window is a down text dialog*/

#define  FATHER_IS_DOWN_TEXT_DIALOG 1
#define  WARNING_WINDOW_ID 99
#define  WARNING_WINDOW_BUTTON_ID 98

#define  LOGIN_ID_DIALOG  411
#define  LOGIN_PASSWORD   412
#define  LOGIN_LOGIN_BUTTON 413
#define  LOGIN_QUTI_BUTTON  414
#define  LOGIN_REGISTER_BUTTON 415
#define  LOGIN_CHOOSE_KIND   416

#define  REGISTER_NAME_DIALOG 450
#define  REGISTER_IDCARD_DIALOG 451
#define  REGISTER_BIRTHDAY_DIALOG 452
#define  REGISTER_SEX_CHOOSE  453
#define  REGISTER_NATION_DIALOG  455
#define  REGISTER_STUSORT_DOWNTEXT 456
#define  REGISTER_MAJOR_DIALOG  457
#define  REGISTER_CLASSID_DIALOG 458
#define  REGISTER_DEPARTMENT_DOWNTEXT 459
#define  REGISTER_OK_BUTTON  460 
#define  REGISTER_PASSWORD_DIALOG 461 
#define  REGISTER_PASSWORD_AGAIN  462 
#define  REGISTER_BACK_BUTTON  463 
 
#define   STUDENT_MENU_HEADER  100
#define   STUDENT_INFORMATION  111
#define   STUDENT_CLASS                 112
#define   STUDENT_SCORES              113
#define   STUDENT_HELP                   114
#define   STUDENT_ABOUT                115
#define   STUDENT_INFORMATION_MY_INFO 121
#define   STUDENT_INFORMATION_EDIT_INFO 122
#define   STUDENT_INFORMATION_EXIT        123
#define   STUDENT_INFORMATION_LOGIN        130
#define   STUDENT_CLASS_TABLE    124
#define   STUDENT_CLASS_TEACHER 125
#define   STUDENT_CLASS_CHOOSE  126
#define   STUDENT_SCORES_MYSCORE 127
#define   STUDENT_HELP_HELP_INFO  128
#define   STUDENT_ABOUT_THIS_SYSTEM 129
#define   STUDENT_INFORMATION_EDITBASEINFO 141
#define   STUDENT_INFORMATION_EDITSCHOOLINFO 142
#define   STUDENT_INFORMATION_EDITPASSWORD 143
#define   STUDENT_EDIT_TRUENAME   144
#define   STUDENT_EDIT_BIRTHDAY  145
#define   STUDENT_EDIT_IDCARD   146
#define   STUDENT_EDIT_NATION   147
#define   STUDENT_EDIT_TEL   148
#define   STUDENT_EDIT_OKBUTTON   149
#define   STUDENT_EDIT_OLDPASSWORD   150
#define   STUDENT_EDIT_NEWPASSWORD   151
#define   STUDENT_EDIT_AGAINPASSWORD  152
#define   STUDENT_EDIT_PASSWORDOK  153


#define    MANAGER_INFORMATION   311
#define    MANAGER_CLASS                 312
#define    MANAGER_DEPARTMENT     313
#define    MANAGER_HELP                   314
#define    MANAGER_ABOUT                315
#define    MANAGER_INFORMATION_EDIT  321
#define    MANAGER_INFORMATION_SEARCH  322
#define    MANAGER_INFORMATION_LOGIN     330
#define    MANAGER_INFORMATION_EXIT  323
#define    MANAGER_CLASS_NEW                 325
#define    MANAGER_CLASS_SHOW                 326
#define    MANAGER_CLASS_EDIT                 327
#define    MANAGER_DEPARTMENT_NEW     324        
#define    MANAGER_HELP_HELP_INFO   328
#define    MANAGER_ABOUT_THIS_SYSTEM    329
#define    MANAGER_INFORMATION_EDIT_OLD_PASSWORD  361
#define    MANAGER_INFORMATION_EDIT_NEW_PASSWORD  362
#define    MANAGER_INFORMATION_EDIT_NEW_AGAIN  363
#define    MANAGER_INFORMATION_EDIT_OK_BUTTON  364
#define    MANAGER_DEPARTMENT_NEW_OK_BUTTON   367
#define    MANAGER_CLASS_NEW_CLASSNAME 368
#define    MANAGER_CLASS_NEW_CLASSID 369
#define    MANAGER_CLASS_NEW_TEACHERNAME 370
#define    MANAGER_CLASS_NEW_TEACHERID 371
#define    MANAGER_CLASS_NEW_POSITION 372
#define    MANAGER_CLASS_NEW_TIMEWEEK 373
#define    MANAGER_CLASS_NEW_TIMERANK 374
#define    MANAGER_CLASS_NEW_OK 375


#define  TEACHER_INFORMATION  211
#define  TEACHER_CLASS  212
#define  TEACHER_SCORES  213
#define  TEACHER_HELP  214
#define  TEACHER_ABOUT  215
#define  TEACHER_INFORMATION_MYINFO 221
#define  TEACHER_INFORMATION_EDIT  222
#define  TEACHER_INFORMATION_EXIT 223
#define  TEACHER_CLASS_MYCLASS  224
#define  TEACHER_CLASS_STU  225
#define  TEACHER_CLASS_EDIT  226
#define  TEACHER_SCORES_INPUT  227
#define  TEACHER_HELP_HELP_INFO  228
#define  TEACHER_ABOUT_ABOUT  229

#endif 